theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

show_downloads: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"